title: Adwatch Innsbruck
baseURL: 'https://malinauer.github.io'
languageCode: de-DE
defaultContentLanguage: de
theme: papermod
menu:
  main:
    - identifier: ueber
      name: Über die Website
      url: ueber/
      weight: -90
    - identifier: posts
      name: Watchblog
      url: posts/
      weight: -110
    - identifier: resourcen
      name: Resourcen
      url: resourcen/
      weight: -100
